version: "3.9"
services:
  server:
    build: ./svelte
    container_name: "server"
    ports:
      - "80:80"
    depends_on:
      - "api"
    restart: always

  api:
    build: ./api
    container_name: "api"
    depends_on:
      - "database"
    environment:
      PORT: "8080"
      NODE_ENV: "production"
    expose:
      - "8080"
    restart: always

  database:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
