version: "3.9"
services:
  server:
    build: ./svelte
    ports:
      - "80:80"
    depends_on:
      - "api"
    restart: always

  api:
    build: ./api
    depends_on:
      - "database"
    environment:
      PORT: "8080"
      NODE_ENV: "production"
      mongodb: "mongodb://database:27017/public-planner"
    expose:
      - "8080"
    restart: always

  database:
    image: mongo
    restart: always
    volumes:
      - "public-planner-mongodb:/data/db"
    expose:
      - "27017"

volumes:
  public-planner-mongodb:
